trigger:
- main

pool:
  name: Default # Ensure this matches the name of your agent pool

steps:
- script: |
    curl -LO https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
    unzip terraform_1.0.11_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform --version
  displayName: 'Install Terraform'

- script: |
    terraform init
    terraform validate
  displayName: 'Validate Terraform Configuration'
  workingDirectory: './'
'
