trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
- task: UseTerraform@0
  inputs:
    command: 'validate'
